# Generated by Django 3.0.5 on 2020-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('time13_1', models.CharField(default=' ', max_length=20)),
                ('time13_2', models.CharField(default=' ', max_length=20)),
                ('time14_1', models.CharField(default=' ', max_length=20)),
                ('time14_2', models.CharField(default=' ', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
