# Generated by Django 3.0.5 on 2020-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time17_1',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='time17_2',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='time18_1',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='time18_2',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='time20_1',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='time20_2',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
